DROP TABLE IF EXISTS Configuration
;
DROP TABLE IF EXISTS AccountTypes
;
DROP TABLE IF EXISTS Suppliers
;
DROP TABLE IF EXISTS PaymentFiles
;
DROP TABLE IF EXISTS Payments
;
CREATE TABLE Configuration
(
  BackendFile TEXT PRIMARY KEY
)
;
CREATE TABLE AccountTypes
(
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL
) 
;
CREATE TABLE Suppliers
(
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
	AccountTypeId INTEGER NOT NULL,
	AccountNo TEXT NOT NULL,
	FOREIGN KEY(AccountTypeId) REFERENCES AccountTypes(Id)
) 
;
CREATE TABLE PaymentFiles
(
	Id INTEGER PRIMARY KEY,
	Name TEXT NOT NULL,
  Status TEXT NOT NULL
) 
;
CREATE TABLE Payments
(
	Id INTEGER PRIMARY KEY,
	PaymentFileId INTEGER NOT NULL,
	DueDate TEXT NOT NULL,
  AccountTypeName TEXT NOT NULL,
  AccountNo TEXT NOT NULL,
	SupplierName TEXT NOT NULL,
	Amount DOUBLE NOT NULL,
	Reference TEXT NOT NULL,
	FOREIGN KEY(PaymentFileId) REFERENCES PaymentFiles(Id)
)
;
