/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 2010-dec-13, 16:04:55
 */

package se.dids.paysup;

import java.io.File;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author david
 */
public class MainFrame extends javax.swing.JFrame {

    boolean firstRun;

    /** Creates new form MainFrame */
    public MainFrame(boolean firstRun) {
        this.firstRun = firstRun;
        initComponents();
    }

    public void showFrame() {
      setVisible(true);
      if (firstRun) {
        NewDatabaseDialog form = new NewDatabaseDialog(this, true);
        form.setVisible(true);
      } else {
        File oldFile = new File((String)Configuration.getInstance().getConfig().getProperty("default_database"));
        DbHandler.getInstance().initialize(oldFile);
      }
      load();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    supplierList = new javax.swing.JList();
    nameTextField = new javax.swing.JTextField();
    accountTextField = new javax.swing.JTextField();
    amountTextField = new javax.swing.JTextField();
    dateTextField = new javax.swing.JTextField();
    referenceTextField = new javax.swing.JTextField();
    accountTypesComboBox = new javax.swing.JComboBox();
    updateButton = new javax.swing.JButton();
    clearButton = new javax.swing.JButton();
    totalAmountTextField = new javax.swing.JTextField();
    generateButton = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    paymentsTable = new javax.swing.JTable();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    newDatabaseMenuItem = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    supplierList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    supplierList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(supplierList);

    updateButton.setText("Add");
    updateButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        updateButtonActionPerformed(evt);
      }
    });

    clearButton.setText("Clear");

    generateButton.setText("Generate");

    paymentsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane2.setViewportView(paymentsTable);

    fileMenu.setText("File");

    newDatabaseMenuItem.setText("New Database...");
    newDatabaseMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newDatabaseMenuItemActionPerformed(evt);
      }
    });
    fileMenu.add(newDatabaseMenuItem);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(generateButton)))
          .addGroup(layout.createSequentialGroup()
            .addComponent(accountTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(layout.createSequentialGroup()
              .addComponent(updateButton)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(clearButton))
            .addComponent(referenceTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
        .addGap(38, 38, 38))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(62, 62, 62)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(accountTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(referenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(updateButton)
              .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(generateButton)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void newDatabaseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDatabaseMenuItemActionPerformed
      new NewDatabase().setVisible(true);
    }//GEN-LAST:event_newDatabaseMenuItemActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
      // Is this supplier already existing?
      AccountType aT = (AccountType)accountTypesComboBox.getSelectedItem();
      Supplier sup = Supplier.load(aT.getId(), accountTextField.getText());
      if (sup == null) {
        sup = new Supplier(aT.getId(), accountTextField.getText(), nameTextField.getText());
        sup.insert();
      } else {
        // Check if name has changed
        if (! sup.getName().equals(nameTextField.getText())) {
          sup.setName(nameTextField.getText());
          sup.update();
        }
      }
      updateSupplierList();
    }//GEN-LAST:event_updateButtonActionPerformed

  public void updateSupplierList() {
    DefaultListModel listModel = new DefaultListModel();
    listModel.clear();
    List l = Supplier.loadAll();
    for (Iterator iter = l.iterator(); iter.hasNext();) {
        listModel.addElement((Supplier)iter.next());
    }
    supplierList.setModel(listModel);
    supplierList.addListSelectionListener(new ListSelectionListener() {

      public void valueChanged(ListSelectionEvent e) {
        if (! e.getValueIsAdjusting()) {
          JList jL = (JList)e.getSource();
          Supplier selectedSup = (Supplier)jL.getSelectedValue();
          fastType(selectedSup);
        }
      }
    });
  }

  private int getAccountTypeIndex(Supplier sup) {
    int size = accountTypesComboBox.getModel().getSize();
    for (int i = 0; i < size; i++) {
      AccountType aT = (AccountType) accountTypesComboBox.getModel().getElementAt(i);
      if (aT.getId() == sup.getAccountTypeId()) {
        return i;
      }
    }
    throw new RuntimeException("Account Type not found.");
  }

  private void fastType(Supplier sup) {
    accountTypesComboBox.setSelectedIndex(getAccountTypeIndex(sup));
    accountTextField.setText(sup.getAccountNo());
    nameTextField.setText(sup.getName());
  }

  private void load() {
    updateSupplierList();
    List l = AccountType.loadAll();
    for (Iterator iter = l.iterator(); iter.hasNext();) {
      accountTypesComboBox.addItem((AccountType)iter.next());
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField accountTextField;
  private javax.swing.JComboBox accountTypesComboBox;
  private javax.swing.JTextField amountTextField;
  private javax.swing.JButton clearButton;
  private javax.swing.JTextField dateTextField;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JButton generateButton;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JMenuItem newDatabaseMenuItem;
  private javax.swing.JTable paymentsTable;
  private javax.swing.JTextField referenceTextField;
  private javax.swing.JList supplierList;
  private javax.swing.JTextField totalAmountTextField;
  private javax.swing.JButton updateButton;
  // End of variables declaration//GEN-END:variables

}
